FROM apache/superset:4.0.1

ARG USER
ARG FIRSTNAME
ARG LASTNAME
ARG EMAIL
ARG PASSWORD
ARG SUPERSET_SECRET_KEY

ENV PYTHONUNBUFFERED=1
RUN pip install trino

RUN superset db upgrade;
RUN superset fab create-admin \
    --username ${USER} \
    --firstname ${FIRSTNAME} \
    --lastname ${LASTNAME} \
    --email ${EMAIL} \
    --password ${PASSWORD};
RUN superset init;