FROM apache/superset

ARG USER
ARG FIRSTNAME
ARG LASTNAME
ARG EMAIL
ARG PASSWORD
ARG SUPERSET_SECRET_KEY

RUN superset fab create-admin \
    --username ${USER} \
    --firstname ${FIRSTNAME} \
    --lastname ${LASTNAME} \
    --email ${EMAIL} \
    --password ${PASSWORD}

RUN superset db upgrade
RUN superset init